vdb endpoint does not work with vdb.im urls #8
lionel-panhaleux/krcg-api pull request #9
Opened 2022-07-11 11:22 UTC by bszymkow

fixes #8

2022-07-17 06:08 UTC, bszymkow commented
Updates other test files to ensure all tests are passing. Summary of changes:
- Added empty bodies to POST operations with application/json content-types
- Fixed logic in /convert route to look at flake.request.content_type instead of null comparisons for a more explicit, readable and function code
- Updated various tests that have different responses now that more cards have been added and more TWDA entries exist

2022-08-08 14:29 UTC, lionel-panhaleux requested changes
There are a lot of changes that are not tied to the modification you want to make. I'm happy to rework the PR if you don't have the time, I'll try to do it this week if that's OK with you

2022-08-08 14:29 UTC, lionel-panhaleux commented on tests/test_card_search.py
> +# from itsdangerous import json
spurious import

2022-08-08 14:29 UTC, lionel-panhaleux commented on tests/test_card_search.py
> +            "Andr\u00e9 Freitas",
please keep the utf-8 version instead, more readable

2022-08-08 14:29 UTC, lionel-panhaleux commented on test.http
> +@deck = https://vdb.im/decks?id=ebbe31dddce54adc9e8719942b4b2ff1
how is this test file run? I see no modification in the GHub workflows?

2022-08-08 14:29 UTC, lionel-panhaleux commented on krcg_api/api.py
> +
maybe use if / elif / else: we don't want a 500 if the content_type was not properly set. I would argue that defaulting to any content type other than json to try the plain text treatment made more sense than this change.

2022-08-08 14:29 UTC, lionel-panhaleux commented on krcg_api/api.py
> +
Plus this seems to have nothing to do with the PR intent, maybe simply remove?

2022-08-08 14:29 UTC, lionel-panhaleux commented on tests/test_candidates.py
> +        },
keep the original utf-8 line

2022-08-08 14:29 UTC, lionel-panhaleux commented on tests/test_candidates.py
> +            "card": "Pentex\u2122 Subversion",
Keep the original utf-8 line

2022-08-08 14:29 UTC, lionel-panhaleux commented on tests/test_card.py
>      response = client.get("/card/The%20Line")
So many changes here that have no impact... I don't see what is the actual change in it

2022-08-08 14:29 UTC, lionel-panhaleux commented on tests/test_card_search.py
> +    response = client.post("/card_search", json={})
does that change anything?

2022-08-08 19:24 UTC, lionel-panhaleux commented
Thanks for the PR. I reworked it a bit: the VDB domain change is @ efa4719b7766ece24bff436795370ce48dc2fe00. If you're curious, you can check the fixed I made for the flask upgrade and the few tests that were failing (some because of the flask upgrade, some because there were changes in the TWDA 2020 decks), in the next commit a49fbd8bb7d22fc2cee1111a9155d01a550c4ff8 

Packaged, released and deployed to the main server.

2022-08-08 19:24 UTC, closed without merging